baseURL = "https://joshhighet.com/"
buildDrafts = false
buildFuture = false
buildExpired = false
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
googleAnalytics = "UA-134175149-1"
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "josh!"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Josh Highet"
  email = "hi@joshhighet.com"
  description = "josh!"
  bio = ""
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "no such page."

  [params.contact]
    github = "https://github.com/joshhighet"
    facebook = "https://facebook.com/jhighet"
    keybase = "https://keybase.io/joshhighet"
    medium = "https://medium.com/@joshhighet"
    twitter = "https://twitter.com/joshhighet"
    youtube = "https://youtube.com/joshhighet"
    instagram = "https://instagram.com/joshhighet"
    linkedin = "https://linkedin.com/in/joshhighet"
    snapchat = "https://snapchat.com/add/joshhighet"
    soundcloud = "https://soundcloud.com/joshhighet"
    reddit = "https://www.reddit.com/user/joshhighet"
    quora = "https://www.quora.com/profile/Josh-Highet"
    spotify = "https://open.spotify.com/user/joshhighet"
    apple = "https://itunes.apple.com/profile/joshhighet"
    lastfm-square = "https://www.last.fm/user/joshhighet"
    firefox = "https://community.mozilla.org/people/joshhighet/"
    kickstarter = "https://www.kickstarter.com/profile/joshhighet"
